mood_interest_choices = {
    'a': 'Relaxing',
    'b': 'Energetic',
    'c': 'Social',
    'd': 'Adventurous',
    'e': 'Creative',
    'f': 'Reflective',
    'g': 'Productive',
    'h': 'Spontaneous',
    'i': 'Outdoor activities',
    'j': 'Indoor activities',
    'k': 'Social gatherings',
    'l': 'Arts and crafts',
    'm': 'Sports and fitness',
    'n': 'Food and cooking',
    'o': 'Cultural experiences',
    'p': 'Educational pursuits',
    'q': 'Nature exploration', 
    'r': 'Entertainment', 
    's': 'Relaxation and self-care', 
    't': 'Adventure sports', 
    'u': 'Volunteer work', 
    'v': 'DIY projects', 
    'w': 'Gaming and recreation'
}